### PR TITLE
Adding group parameter to dimensions 

### PR DESCRIPTION
**Pull request by akariv**
(to record the original, compound, dimension)

@pudo can you please take a look?

+ some minor Python3 compatibility fixes

### CODE REVIEW

**Comment by pudo** [comment]
Sorry, I don't get it. Can you explain a little?

**Comment by akariv** [comment]
Yes. In FDP we have compound dimensions such as:
```json
      "administrative-classification": {
        "attributes": {
          "admin1": {
            "source": "admin1"
          },
          "admin2_code": {
            "parent": "admin1",
            "source": "admin2 (code)"
          },
          "admin2_label": {
            "labelfor": "admin2_code",
            "source": "admin2 (label)"
          },
          "admin3_code": {
            "parent": "admin2_code",
            "source": "admin3 (code)"
          },
          "admin3_label": {
            "labelfor": "admin3_code",
            "source": "admin3 (label)"
          },
          "admin4_code": {
            "parent": "admin3_code",
            "source": "admin4 (code)"
          },
          "admin4_label": {
            "labelfor": "admin4_code",
            "source": "admin4 (label)"
          },
          "admin5_code": {
            "parent": "admin4_code",
            "source": "admin5 (code)"
          },
          "admin5_label": {
            "labelfor": "admin5_code",
            "source": "admin5 (label)"
          },
          "admin6_code": {
            "parent": "admin5_code",
            "source": "admin6 (code)"
          },
          "admin6_label": {
            "labelfor": "admin6_code",
            "source": "admin6 (label)"
          }
        },
        "classificationType": "administrative",
        "dimensionType": "classification",
        "primaryKey": [
          "admin1",
          "admin2_code",
          "admin3_code",
          "admin4_code",
          "admin5_code",
          "admin6_code"
        ]
      },
```

When converting to a Babbage model, I split this dimension to 6 separate dimensions, such as:
```json
    "admin2_code": {
      "attributes": {
        "admin2_code": {
          "column": "admin2_code",
          "label": "admin2_code"
        },
        "admin2_label": {
          "column": "admin2_label",
          "label": "admin2_label"
        }
      },
      "key_attribute": "admin2_code",
      "label": "administrative-classification.admin2_code",
      "label_attribute": "admin2_label"
    },
```

The problem is that this way, the fact that the dimensions came from a common origin is lost.
Also, in the API, results appear as ``"admin2_code.admin2_code"`` or ``"admin2_code.admin2_label"`` whereas I'd like them to be ``"administrative-classification.admin2_code"``` etc.

By adding a ``"group": "administrative-classification"`` property, I can give each dimension a better ``ref`` which is more consistent with the old API and reflects the dimension definition as it appears in the FDP.

**Comment by pudo** [comment]
Ah, I'm beginning to see. I wonder, though, if it wouldn't be even better to add hierarchies support to babbage. I've got free time today :)

**Comment by pudo** [comment]
For hierarchies, I was hoping to follow the model conventions laid out by cubes: https://cubes.readthedocs.org/en/latest/model.html#level

**Comment by akariv** [comment]
Well, it could be nice to have them :)
However, since FDP doesn't support them, it would probably be an overkill for this scenario.

**Comment by akariv** [comment]
@pudo I spent some time thinking on the best approach here, taking into account the cubes reference.
If I understood correctly, cubes' dimensions always have a list of levels within them, each of which contains a list of attributes.
With babbage, we basically lay out all the levels, each with its own set of attributes.
In order to support such hierarchies (albeit a simpler version of them), without breaking the entire model and remain backward compatible, I suggest one of these possible implementations:

The implicit way - in which each babbage dimension might contain a new property `level_of`, which would be the id of the upper hierarchy (for example, for the `year` dimension we might add a `level_of: "time"` property). 
The explicit way - in which we would add a new mapping to the model (alongside `dimensions` and `measures`), which would define the dimension hierarchies (only for those dimensions for which it's relevant or needed). For example, we might have
```json
"dimensions": { ...
  "month": { 
     "attributes" : {
         "month": ...
         "month_name": ...
     }
  }  
  ...
},
"measures": { ... },
"levels": {
  "time": ["year", "month", "day"]
}
```

Both implementations are quite simple. In the above case, it would affect the way `month` is referenced - instead of `month.month`, it would become `time.month`.

Please let me know what you think.

**Comment by pudo** [comment]
I quite like the explicit style you're proposing! It's not what other OLAP tools do, but it could work quite nicely for us to add support for hierarchies while keeping the basic API clean. I would perhaps propose a bit more JSON decorum so that we can make neat things happen in the UI:

```json
{
  "dimensions": {},
  "measures": {},
  "hierarchies": {
    "time": {
      "label": "Time",
      "levels": ["year", "month", "day"]
   }
}
```
WDYT?

Adding this to the data model should be totally simple, and it allows me to get rid of a lot of the hierarchies code I need in offenerhaushalt.de right now: https://github.com/okfde/offenerhaushalt.de/blob/master/sites/berlin.yaml#L24

I guess it'd be very fun to see how APIs like the aggregator should treat hierarchies, I could well imagine that it might be possible to query a dimension by a special hierarchies syntax which makes sure that things are done hierarchically. That would mean that hierarchy names and dimension/measure names should not conflict -- seems like a reasonable idea anyway :)

**Comment by akariv** [comment]
@pudo I'm glad you like it! I also agree that the more elaborate JSON syntax you suggested is indeed better.
I'll give it a try and let you know once it's working.

**Comment by akariv** [comment]
@pudo I think this is done - can you please take a look?

**Comment by pudo** [comment]
This is brilliant, I'm absolutely excited at how concise this is. Two comments (feel free to merge, though): 

1. I don't quite understand why the attribute name adapts to being part of a hierarchy. Wouldn't this be many to many (i.e. can one dimension not show up in multiple hierarchies?). I'd just like to understand why the ref thing happens, and don't quite yet. 

2. It might be cool to ensure that all the levels for a given dimension are valid refs.

**Comment by akariv** [comment]
Hi @pudo, 
1. The idea here is that usually (?) for hierarchies you'll encounter something like (_schematically_):
```yaml
dimensions:
  - year_dim:
       attributes: year
  - month_dim:
        attributes: month, month_name
  - day_dim:
        attributes: day
- hierarchies:
    - time:
         levels: year_dim, month_dim, day_dim
```

In these cases, you'd like to refer to the `year` attribute as `time.year` instead of `year_dim.year`. This is relevant for the `cuts` api parameter as well as how stuff looks like in the responses.

2. I agree, I'll add this check.

3. Indeed - wasn't aware of it till now :)

**Comment by pudo** [comment]
Ah, but then ``time.year`` is effectively an alias for ``year_dim.year``, no? Wouldn't it be better to make it such that ``time.year`` resolves and returns the same object as ``year_dim.year``, instead of properly renaming it (which becomes arbitrary once a dimension is mentioned in multiple hierarchies).

**Comment by akariv** [comment]
Alright - what about the results? Do you think we should show
`year_dim.year` in there or `time.year`?

**Comment by pwalsh** [comment]
I'm not up on the internals with what goes on for this mapping, but I'm going to drive-by vote that based on the example above, I'd much rather we are exposing APIs like `time.year` than `year_dim.year`.

**Comment by akariv** [comment]
@pudo - this is what I went with, lmk what  you think.

Each concept now has a list of 'aliases' which contain the original ref and (right now) one optional alias.
When matching concepts vs refs, we check the aliases as well.
Lastly, the concept remembers the matched ref and use it when binding to the physical db column.

The result of this is we now support both `time.year` and `year_dim.year` as refs for dimensions / drilldowns etc. The attribute will be referred in the results the same way it was used in the request. That is, if I request `time.year` I'll get results with `time.year` and if I use `year_dim.year` the results will use this alias. All other data will be exactly the same.

**Comment by akariv** [comment]
@pudo any final comments before I merge this :smile: ?

**Comment by pudo** [comment]
Looks good to me :+1:

**Pull request merged**
