### PR TITLE
Star tables support

### PR DESCRIPTION
**Pull request by jbothma**

### CODE REVIEW

**Comment by jbothma** [comment]
Sorry, this was meant to be against our fork

**Comment by pwalsh** [comment]
@jbothma lots of stuff here, and I'm especially interested if you re going for star schema support ( https://github.com/openspending/babbage/issues/3 ). Would be great to co-ordinate with you/learn if you plan to push some changes back upstream.

**Comment by jbothma** [comment]
Ah thank's for referencing #3 - forgot to look in your issues when I started it. I made a new PR at https://github.com/openspending/babbage/pull/18 for this since the branch I started this PR with is based on our fork.

**Comment by pudo** [comment]
@pwalsh just to make sure this is clear: it's you or @akariv who are the "merge czars" on this, not me, right?

**Comment by pwalsh** [comment]
@akariv yes

**Pull request closed without merging**
